### ISSUE TITLE
Multiple No visible @interface errors

### ISSUE THREAD

**Issue by argoel** [jessesquires/JSQSystemSoundPlayer#14]
Hello

I am suddenly facing the following errors. The only change I did was do pod update. So it installed the latest JSQSystemSoundPlayer.
![screen shot 2015-05-27 at 10 53 56 pm](https://cloud.githubusercontent.com/assets/2237789/7853451/52920b98-04c3-11e5-825c-3eaabd3740ed.png)

Any immediate response? Thanks!

**Comment by jessesquires** [comment]
yep - check the release notes.

https://github.com/jessesquires/JSQSystemSoundPlayer/releases

**Comment by argoel** [comment]
Thanks a lot!
