### ISSUE TITLE
no visible @interface for 'JSQSystemSoundPlayer' declares the selector 'playAlertSoundWithFilename:fileExtension:'

### ISSUE THREAD

**Issue by atilladeniz** [jessesquires/JSQSystemSoundPlayer#33]
/Users/Ati/Desktop/Chat/Community Chat/JSQMessagesViewController/Categories/JSQSystemSoundPlayer+JSQMessages.m:67:46: error: no visible @interface for 'JSQSystemSoundPlayer' declares the selector 'playAlertSoundWithFilename:fileExtension:'
        [[JSQSystemSoundPlayer sharedPlayer] playAlertSoundWithFilename:fileName fileExtension:kJSQSystemSoundTypeAIFF];
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Ati/Desktop/Chat/Community Chat/JSQMessagesViewController/Categories/JSQSystemSoundPlayer+JSQMessages.m:70:46: error: no visible @interface for 'JSQSystemSoundPlayer' declares the selector 'playSoundWithFilename:fileExtension:'
        [[JSQSystemSoundPlayer sharedPlayer] playSoundWithFilename:fileName fileExtension:kJSQSystemSoundTypeAIFF];
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.

**Comment by atilladeniz** [comment]
if (asAlert) {
        [[JSQSystemSoundPlayer sharedPlayer] playAlertSoundWithFilename:fileName fileExtension:kJSQSystemSoundTypeAIFF completion:nil];
        
    } else {
        [[JSQSystemSoundPlayer sharedPlayer] playSoundWithFilename:fileName fileExtension:kJSQSystemSoundTypeAIFF completion:nil];
    }

after i put this in the file than it works

**Comment by jessesquires** [comment]
Thanks @atilladeniz ! 😄 

This isn't a problem with `JSQSystemSoundPlayer`.

If using `JSQMessagesViewController`, you should install through Cocoapods. `JSQMessagesViewController` depends on an older version of this library.
