### ISSUE TITLE
How to adjust volume?

### ISSUE THREAD

**Issue by MHX792** [jessesquires/JSQSystemSoundPlayer#40]
Hi!

How to make `JSQSystemSoundPlayer` follow the volume settings of the device? The sound is just too loud...

Thanks!

**Comment by jessesquires** [comment]
Hey @MHX792 😄 

You can't adjust the volume for System Sound Services — it uses the user's current settings. Playing sounds via `JSQSystemSoundPlayer` goes through the same pipeline as system alerts/sounds, for example, the sound played when receiving a text message.

See the README for more details. If you need to control volume, you'll need to use `AVFoundation`.
