### ISSUE TITLE
Curious why sound is not playing in simulator ?

### ISSUE THREAD

**Issue by yarodevuci** [jessesquires/JSQSystemSoundPlayer#41]
@jessesquires Tested in simulator not working
Only on device

**Comment by jessesquires** [comment]
Hey @yarodevuci 😄 

Yeah, depending on your version of Xcode/simulators, there are regressions/bugs here.

**Comment by jessesquires** [comment]
To clarify: Apple bugs, not bugs with this framework. 😊
