### ISSUE TITLE
support url

### ISSUE THREAD

**Issue by YongLeiCHU** [jessesquires/JSQSystemSoundPlayer#48]
## New issue checklist

- [ ] I have read all of the [`README`](https://github.com/jessesquires/JSQDataSourcesKit/blob/develop/README.md) and [documentation](http://www.jessesquires.com/JSQDataSourcesKit/).
- [ ] I have reviewed the [contributing guidelines](https://github.com/jessesquires/HowToContribute).
- [ ] I have searched [existing issues](https://github.com/jessesquires/JSQDataSourcesKit/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- Library version:
- OS version:
- Devices/Simulators:
- Reproducible in the demo project (Yes/No): 
- Any related issues:

**Comment by jessesquires** [comment]
Thanks @YongLeiCHU !

Please open a new issue and explain what you need/want.
